Repository AY2223S2-CS2103T-T12-1/tp, pull requests merged in 2023-04, with the labels that each got.

#184 Fix various documentation/user prompt errors
  docs/UserGuide.md
  src/main/java/seedu/patientist/logic/commands/AddPatientCommand.java
Labels: documentation, bugfix

#186 Update PPP for Lin Chieh
  docs/AboutUs.md
  docs/index.md
  docs/team/euph00.md
Labels: documentation

#187 Add ward in person cards and details screen
  src/main/java/seedu/patientist/logic/commands/AddPatientStatusCommand.java
  src/main/java/seedu/patientist/logic/commands/AddPatientToDoCommand.java
  src/main/java/seedu/patientist/logic/commands/CommandResult.java
  src/main/java/seedu/patientist/logic/commands/DeleteCommand.java
  src/main/java/seedu/patientist/logic/commands/DeletePatientStatusCommand.java
  src/main/java/seedu/patientist/logic/commands/DeletePatientToDoCommand.java
  src/main/java/seedu/patientist/logic/commands/EditCommand.java
  src/main/java/seedu/patientist/logic/commands/ExitCommand.java
  src/main/java/seedu/patientist/logic/commands/FindCommand.java
  src/main/java/seedu/patientist/logic/commands/FindPatientCommand.java
  src/main/java/seedu/patientist/logic/commands/FindStaffCommand.java
  src/main/java/seedu/patientist/logic/commands/HelpCommand.java
  src/main/java/seedu/patientist/logic/commands/ListCommand.java
  src/main/java/seedu/patientist/logic/commands/ListPatientsCommand.java
  src/main/java/seedu/patientist/logic/commands/ListStaffCommand.java
  src/main/java/seedu/patientist/logic/commands/ListWardPatientsCommand.java
  src/main/java/seedu/patientist/logic/commands/ListWardStaffCommand.java
  src/main/java/seedu/patientist/logic/commands/ListWardsCommand.java
  src/main/java/seedu/patientist/logic/commands/UpdatePatientWardCommand.java
  src/main/java/seedu/patientist/logic/commands/ViewCommand.java
  src/main/java/seedu/patientist/model/Patientist.java
  src/main/java/seedu/patientist/ui/DetailsPopup.java
  src/main/java/seedu/patientist/ui/MainWindow.java
  src/main/java/seedu/patientist/ui/PatientCard.java
  src/main/java/seedu/patientist/ui/PersonListPanel.java
  src/main/java/seedu/patientist/ui/StaffCard.java
  src/main/resources/view/DetailsPopup.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PatientistTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/WardListCard.fxml
  src/test/java/seedu/patientist/logic/commands/CommandResultTest.java
  src/test/java/seedu/patientist/logic/commands/ExitCommandTest.java
  src/test/java/seedu/patientist/logic/commands/HelpCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ViewCommandTest.java
Labels: bugfix

#190 Fix bugs found in mock PE
  src/main/java/seedu/patientist/model/person/patient/Patient.java
  src/main/java/seedu/patientist/ui/DetailsPopup.java
  src/main/resources/view/DetailsPopup.fxml
Labels: bugfix, ui

#189 Fix and improve UG.
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addpat.png
  docs/images/addpatstatus.png
  docs/images/addpattodo.png
  docs/images/addward.png
  docs/images/components.png
  docs/images/delete.png
  docs/images/edit.png
  docs/images/find.png
  docs/images/lspat.png
  docs/images/lsward.png
  docs/images/trfward.png
  docs/images/view.png
Labels: documentation, bugfix

#193 docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#194 Update pzhengze's PPP
  docs/team/pzhengze.md
Labels: documentation

#191 Test cases and bugs fixed for lswardpat
  src/main/java/seedu/patientist/logic/commands/UpdateWardCommand.java
  src/main/java/seedu/patientist/logic/parser/ListWardPatientsCommandParser.java
  src/main/java/seedu/patientist/logic/parser/ListWardStaffCommandParser.java
  src/main/java/seedu/patientist/logic/parser/PatientistParser.java
  src/main/java/seedu/patientist/logic/parser/UpdatePatientWardParser.java
  src/main/java/seedu/patientist/logic/parser/UpdateWardParser.java
  src/test/java/seedu/patientist/logic/commands/UpdatePatientWardCommandTest.java
  src/test/java/seedu/patientist/logic/commands/UpdateWardCommandTest.java
  src/test/java/seedu/patientist/logic/parser/ListWardPatientsCommandParserTest.java
  src/test/java/seedu/patientist/logic/parser/ListWardStaffCommandParserTest.java
  src/test/java/seedu/patientist/logic/parser/UpdatePatientWardParserTest.java
  src/test/java/seedu/patientist/logic/parser/UpdateWardParserTest.java
Labels: bugfix

#198 Update Zheng Ze's PPP
  docs/team/pzhengze.md
Labels: documentation
