Repository AY2223S2-CS2103T-T12-1/tp, pull requests merged in 2023-03, with the labels that each got.

#43 Update Non Functional Requirement in DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/pzhengze.png
  docs/team/pzhengze.md
Labels: documentation

#52 Update _config.yml
  docs/_config.yml
Labels: documentation, bugfix

#53 Update CI banner in README.md
  README.md
Labels: documentation, bugfix

#54 Updated AboutUs and portfolio document
  docs/AboutUs.md
  docs/images/jinnieshin.png
  docs/team/jinnieshin.md
Labels: documentation

#63 Implements Patient class + ID number + Status details, and tests
  src/main/java/seedu/patientist/MainApp.java
  src/main/java/seedu/patientist/model/Patientist.java
  src/main/java/seedu/patientist/model/person/patient/Patient.java
  src/main/java/seedu/patientist/model/person/patient/PatientIdNumber.java
  src/main/java/seedu/patientist/model/person/patient/PatientStatusDetails.java
  src/main/java/seedu/patientist/model/person/staff/Staff.java
  src/main/java/seedu/patientist/model/ward/Ward.java
  src/test/java/seedu/patientist/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/patientist/logic/commands/ClearCommandTest.java
  src/test/java/seedu/patientist/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/patientist/logic/commands/EditCommandTest.java
  src/test/java/seedu/patientist/logic/commands/FindCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListCommandTest.java
  src/test/java/seedu/patientist/model/PatientistTest.java
  src/test/java/seedu/patientist/model/person/patient/PatientIdNumberTest.java
  src/test/java/seedu/patientist/model/person/patient/PatientTest.java
  src/test/java/seedu/patientist/storage/JsonPatientistStorageTest.java
  src/test/java/seedu/patientist/storage/JsonSerializablePatientistTest.java
  src/test/java/seedu/patientist/storage/StorageManagerTest.java
  src/test/java/seedu/patientist/testutil/PatientBuilder.java
  src/test/java/seedu/patientist/testutil/PersonBuilder.java
  src/test/java/seedu/patientist/testutil/TypicalPatients.java
  src/test/java/seedu/patientist/testutil/TypicalPersons.java
Labels: feature, logic

#66 Update help to show correct UG.
  src/main/java/seedu/patientist/ui/HelpWindow.java
Labels: bugfix, ui

#64 Update AddCommand to add Patients
  src/main/java/seedu/patientist/MainApp.java
  src/main/java/seedu/patientist/logic/commands/AddCommand.java
  src/main/java/seedu/patientist/logic/parser/AddCommandParser.java
  src/main/java/seedu/patientist/logic/parser/CliSyntax.java
  src/main/java/seedu/patientist/logic/parser/ParserUtil.java
  src/main/java/seedu/patientist/model/person/patient/Patient.java
  src/main/java/seedu/patientist/model/person/patient/PatientIdNumber.java
  src/main/java/seedu/patientist/model/util/SampleDataUtil.java
  src/main/java/seedu/patientist/storage/JsonAdaptedPerson.java
  src/main/java/seedu/patientist/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializablePatientistTest/duplicatePatientPatientist.json
  src/test/data/JsonSerializablePatientistTest/invalidPatientPatientist.json
  src/test/data/JsonSerializablePatientistTest/typicalPatientPatientist.json
  src/test/java/seedu/patientist/logic/LogicManagerTest.java
  src/test/java/seedu/patientist/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/patientist/logic/commands/AddCommandTest.java
  src/test/java/seedu/patientist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/patientist/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/patientist/logic/parser/PatientistParserTest.java
  src/test/java/seedu/patientist/model/person/patient/PatientTest.java
  src/test/java/seedu/patientist/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/patientist/storage/JsonPatientistStorageTest.java
  src/test/java/seedu/patientist/storage/JsonSerializablePatientistTest.java
  src/test/java/seedu/patientist/storage/StorageManagerTest.java
  src/test/java/seedu/patientist/testutil/PatientBuilder.java
  src/test/java/seedu/patientist/testutil/PatientUtil.java
  src/test/java/seedu/patientist/testutil/TypicalPatients.java
Labels: story, feature, ui, logic, necessary

#68 Add lspat command.
  src/main/java/seedu/patientist/logic/commands/ListPatientsCommand.java
  src/main/java/seedu/patientist/logic/parser/PatientistParser.java
  src/main/java/seedu/patientist/model/Model.java
  src/main/java/seedu/patientist/model/person/IsPatientPredicate.java
  src/test/java/seedu/patientist/logic/commands/ListPatientCommandTest.java
  src/test/java/seedu/patientist/testutil/TypicalPatients.java
Labels: story, feature, logic, necessary

#74 Fix status not saving bug
  src/main/java/seedu/patientist/storage/JsonAdaptedPerson.java
  src/test/java/seedu/patientist/storage/JsonAdaptedPersonTest.java
Labels: bugfix

#70 Add findpat command
  src/main/java/seedu/patientist/logic/commands/FindPatientCommand.java
  src/main/java/seedu/patientist/logic/commands/ListPatientsCommand.java
  src/main/java/seedu/patientist/logic/parser/FindPatientCommandParser.java
  src/main/java/seedu/patientist/logic/parser/PatientistParser.java
  src/main/java/seedu/patientist/model/person/patient/IsPatientPredicate.java
  src/main/java/seedu/patientist/model/person/patient/PatientIdNumber.java
  src/main/java/seedu/patientist/model/person/patient/PatientNameContainsKeywordsPredicate.java
  src/main/java/seedu/patientist/model/person/patient/PidContainsKeywordsPredicate.java
  src/main/java/seedu/patientist/model/util/SampleDataUtil.java
  src/test/java/seedu/patientist/logic/commands/FindPatientCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListPatientCommandTest.java
  src/test/java/seedu/patientist/logic/parser/FindPatientCommandParserTest.java
  src/test/java/seedu/patientist/model/person/patient/IsPatientPredicateTest.java
  src/test/java/seedu/patientist/model/person/patient/PidContainsKeywordsPredicateTest.java
  src/test/java/seedu/patientist/testutil/PatientBuilder.java
  src/test/java/seedu/patientist/testutil/TypicalPatients.java
Labels: feature, logic

#82 Update View Command to view by index
  src/main/java/seedu/patientist/logic/commands/CommandResult.java
  src/main/java/seedu/patientist/logic/commands/ExitCommand.java
  src/main/java/seedu/patientist/logic/commands/HelpCommand.java
  src/main/java/seedu/patientist/logic/commands/ViewCommand.java
  src/main/java/seedu/patientist/logic/parser/CliSyntax.java
  src/main/java/seedu/patientist/logic/parser/PatientistParser.java
  src/main/java/seedu/patientist/logic/parser/ViewCommandParser.java
  src/main/java/seedu/patientist/model/person/Person.java
  src/main/java/seedu/patientist/ui/DetailsPopup.java
  src/main/java/seedu/patientist/ui/MainWindow.java
  src/main/resources/view/DetailsPopup.fxml
  src/test/java/seedu/patientist/logic/commands/CommandResultTest.java
  src/test/java/seedu/patientist/logic/commands/ExitCommandTest.java
  src/test/java/seedu/patientist/logic/commands/HelpCommandTest.java
Labels: feature, ui, logic

#83 Fix bugs for AddCommand and AddStaffCommand.
  src/main/java/seedu/patientist/logic/commands/AddCommand.java
  src/main/java/seedu/patientist/logic/commands/AddStaffCommand.java
Labels: bugfix

#84 Fix bug when parsing arguments for ListWardPatientsCommand.
  src/main/java/seedu/patientist/logic/commands/ListWardPatientsCommand.java
  src/main/java/seedu/patientist/logic/parser/ListWardPatientsCommandParser.java
  src/main/java/seedu/patientist/logic/parser/PatientistParser.java
  src/main/java/seedu/patientist/logic/parser/ViewCommandParser.java
  src/main/java/seedu/patientist/model/person/patient/PatientInWardPredicate.java
  src/test/java/seedu/patientist/logic/commands/ListWardPatientCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ViewCommandTest.java
  src/test/java/seedu/patientist/logic/parser/ListWardPatientsCommandParserTest.java
  src/test/java/seedu/patientist/logic/parser/ViewCommandParserTest.java
Labels: bugfix, logic

#86 Implementation and testing of Model
  src/main/java/seedu/patientist/model/Model.java
  src/main/java/seedu/patientist/model/Patientist.java
  src/main/java/seedu/patientist/model/person/IdNumber.java
  src/main/java/seedu/patientist/model/person/Person.java
  src/main/java/seedu/patientist/model/person/patient/Patient.java
  src/main/java/seedu/patientist/model/person/staff/Staff.java
  src/main/java/seedu/patientist/model/util/SampleDataUtil.java
  src/main/java/seedu/patientist/model/ward/Ward.java
  src/test/java/seedu/patientist/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/patientist/logic/commands/FindPatientCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListPatientCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListStaffCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListWardPatientCommandTest.java
  src/test/java/seedu/patientist/model/person/AddressTest.java
  src/test/java/seedu/patientist/model/person/IdNumberTest.java
  src/test/java/seedu/patientist/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/patientist/model/person/UniquePersonListTest.java
  src/test/java/seedu/patientist/model/person/patient/IsPatientPredicateTest.java
  src/test/java/seedu/patientist/model/person/patient/PatientTest.java
  src/test/java/seedu/patientist/model/person/staff/IsStaffPredicateTest.java
  src/test/java/seedu/patientist/model/person/staff/StaffTest.java
  src/test/java/seedu/patientist/storage/JsonPatientistStorageTest.java
  src/test/java/seedu/patientist/storage/JsonSerializablePatientistTest.java
  src/test/java/seedu/patientist/storage/StorageManagerTest.java
  src/test/java/seedu/patientist/testutil/StaffBuilder.java
  src/test/java/seedu/patientist/testutil/TypicalPatients.java
  src/test/java/seedu/patientist/testutil/TypicalStaff.java
  src/test/java/seedu/patientist/testutil/TypicalWards.java
  src/test/java/seedu/patientist/testutil/WardBuilder.java
Labels: documentation, feature, logic, necessary, todo, refactoring

#85 Enable Java assertions in build.gradle
  build.gradle
Labels: refactoring

#106 Update DG for changes related to Storage
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation

#99 Update DG for changes related to Model package
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/WardFeatureStep1.puml
  docs/diagrams/WardFeatureStep2.puml
  docs/diagrams/WardFeatureStep3.puml
  docs/diagrams/WardFeatureStep4.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/WardFeatureStep1-After_adding_first_Ward.png
  docs/images/WardFeatureStep2-After_adding_second_Ward.png
  docs/images/WardFeatureStep3-After_adding_Patient_and_Staff.png
Labels: documentation

#108 Update DG for changes related to Logic
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ParserClasses.png
  docs/images/UiClassDiagram.png
Labels: documentation

#107 Update broken tests
  src/main/java/seedu/patientist/model/ModelManager.java
  src/test/java/seedu/patientist/logic/LogicManagerTest.java
  src/test/java/seedu/patientist/logic/commands/AddPatientCommandIntegrationTest.java
  src/test/java/seedu/patientist/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ClearCommandTest.java
  src/test/java/seedu/patientist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/patientist/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/patientist/logic/commands/EditCommandTest.java
  src/test/java/seedu/patientist/logic/commands/FindCommandTest.java
  src/test/java/seedu/patientist/logic/commands/FindPatientCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListPatientCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListStaffCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ViewCommandTest.java
  src/test/java/seedu/patientist/model/ModelManagerTest.java
  src/test/java/seedu/patientist/model/PatientistTest.java
  src/test/java/seedu/patientist/testutil/PatientistBuilder.java
Labels: bugfix

#110 Fix addstf command.
  src/main/java/seedu/patientist/logic/commands/AddPatientCommand.java
  src/main/java/seedu/patientist/logic/commands/AddStaffCommand.java
  src/main/java/seedu/patientist/logic/parser/AddStaffCommandParser.java
  src/test/java/seedu/patientist/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/patientist/logic/parser/AddStaffCommandParserTest.java
  src/test/java/seedu/patientist/testutil/TypicalWards.java
Labels: bugfix

#112 Update diagrams in DG.
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#113 Update Logic class diagram in DG
  docs/images/LogicClassDiagram.png
Labels: documentation

#119 Fix CI
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/Ui.puml
  docs/diagrams/WardFeatureStep3.puml
  docs/images/DeleteSequenceDiagram.png
  docs/team/euph00.md
  src/test/java/seedu/patientist/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/patientist/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/patientist/logic/commands/AddWardCommandTest.java
  src/test/java/seedu/patientist/logic/commands/DeleteWardCommandTest.java
  src/test/java/seedu/patientist/logic/commands/EditCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ListWardPatientCommandTest.java
  src/test/java/seedu/patientist/model/PatientistTest.java
Labels: refactoring

#121 Fix EditCommand
  src/main/java/seedu/patientist/logic/commands/EditCommand.java
  src/test/java/seedu/patientist/logic/commands/EditCommandTest.java
Labels: bugfix

#127 Update DG.
  docs/UserGuide.md
Labels: documentation

#128 Fix UG formatting
  docs/UserGuide.md
Labels: documentation

#131 Add lsward command
  src/main/java/seedu/patientist/logic/commands/CommandResult.java
  src/main/java/seedu/patientist/logic/commands/ExitCommand.java
  src/main/java/seedu/patientist/logic/commands/HelpCommand.java
  src/main/java/seedu/patientist/logic/commands/ListWardsCommand.java
  src/main/java/seedu/patientist/logic/commands/ViewCommand.java
  src/main/java/seedu/patientist/logic/parser/PatientistParser.java
  src/main/java/seedu/patientist/ui/MainWindow.java
  src/main/java/seedu/patientist/ui/WardCard.java
  src/main/java/seedu/patientist/ui/WardListPanel.java
  src/main/resources/view/WardListCard.fxml
  src/main/resources/view/WardListPanel.fxml
  src/test/java/seedu/patientist/logic/commands/CommandResultTest.java
  src/test/java/seedu/patientist/logic/commands/ExitCommandTest.java
  src/test/java/seedu/patientist/logic/commands/HelpCommandTest.java
  src/test/java/seedu/patientist/logic/commands/ViewCommandTest.java
Labels: ui

#141 Make Ui edges round.
  docs/images/Ui.png
  src/main/java/seedu/patientist/ui/DetailsPopup.java
  src/main/java/seedu/patientist/ui/MainWindow.java
  src/main/java/seedu/patientist/ui/PersonCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DetailsPopup.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientistTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: ui

#143 Implement Priority Tag for patient
  src/main/java/seedu/patientist/logic/commands/AddPatientCommand.java
  src/main/java/seedu/patientist/logic/commands/EditCommand.java
  src/main/java/seedu/patientist/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/patientist/logic/parser/CliSyntax.java
  src/main/java/seedu/patientist/logic/parser/ParserUtil.java
  src/main/java/seedu/patientist/model/person/patient/Patient.java
  src/main/java/seedu/patientist/model/tag/PriorityTag.java
  src/main/java/seedu/patientist/model/tag/RoleTag.java
  src/test/java/seedu/patientist/logic/LogicManagerTest.java
  src/test/java/seedu/patientist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/patientist/logic/parser/AddPatientCommandParserTest.java
  src/test/java/seedu/patientist/logic/parser/PatientistParserTest.java
  src/test/java/seedu/patientist/testutil/PatientBuilder.java
  src/test/java/seedu/patientist/testutil/PatientUtil.java
Labels: feature, logic

#142 Update ui result display to wrap text.
  docs/images/Ui.png
  src/main/java/seedu/patientist/model/person/patient/Patient.java
  src/main/resources/view/PatientistTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: ui

#150 Update UG
  docs/UserGuide.md
Labels: documentation
